name: Go Windows Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        go-version: [1.18, 1.19, 1.20, 1.21]
        arch: [amd64, 386, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: |
          if ($env:GOARCH -eq "amd64") {
            $env:GOARCH = "amd64"
          } elseif ($env:GOARCH -eq "386") {
            $env:GOARCH = "386"
          } elseif ($env:GOARCH -eq "arm64") {
            $env:GOARCH = "arm64"
          }
          go test -v ./...
